[package]
name = "messages_actix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
log = "0"
env_logger = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
